
In the session about maps, we used and prepare these data:


```{r, message=FALSE, results='hide'}
# maps
linkMap="https://github.com/EvansDataScience/VAforPM_Spatial/raw/main/worldMap.geojson" 
library(sf)
mapWorld=read_sf(linkMap)

# csv data
linkCSV='https://github.com/EvansDataScience/VAforPM_Spatial/raw/main/merged_data.csv'
dataCSV=read.csv(linkCSV)
dataCSV$HDI_S=as.vector(scale(dataCSV$HDI))
dataCSV$DEM_S=as.vector(scale(dataCSV$DemoIndex))
dataCSV$MIL_S=as.vector(scale(dataCSV$mil_expend))
set.seed(123)
library(cluster)
vars=c('HDI_S','DEM_S','MIL_S')#variables needed
distMatrix=cluster::daisy(dataCSV[,vars])
res.pam=cluster::pam(x=distMatrix,k = 3,cluster.only = F)
dataCSV$cluster=as.factor(res.pam$clustering)
dataCSV$cluster=factor(dataCSV$cluster,
                           levels=c(1,3,2),
                           labels=c("low","mid","best"), 
                           ordered=T)

### updating map
# 'mapWorldVars' is a new map 
mapWorldVars=merge(mapWorld, #map first
                   dataCSV, 
                   by='ISO3') 

# info about safety in the cities
library(rio)
linkCity="https://github.com/EvansDataScience/VAforPM_Spatial/raw/main/citiesloc.xlsx"
SafeCityData=import(linkCity)
SafeCityPoints = st_as_sf(SafeCityData, 
                      coords = c("lng", "lat"),
                      crs = st_crs(mapWorldVars)) # shared

```


Now let me save those maps as a file:

```{r}
#saving
st_write(mapWorldVars, 
         dsn = "mapWorldVars.geojson",
         layer = "mapWorldVars.geojson",
         driver = "GeoJSON")

st_write(SafeCityPoints, 
         dsn = "SafeCityPoints.geojson",
         layer = "SafeCityPoints.geojson",
         driver = "GeoJSON")
```



