---
title: "Dashboards at EVANS UW"
author: "Great student"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows # (Plots appear by ROW)
    social: menu # to share your dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)

###
library(ggplot2)
library(plotly)
library(plyr)

library(sf)

myWeb="https://github.com/EvansDataScience/VAforPM_Dashboard/raw/main/"
mapWorldVars=read_sf(paste0(myWeb,"mapWorldVars.geojson"))
```

[comment]: # (THIS CREATES A TAB)

Static Plots
=======================================================================

[comment]: # (Plots appear by ROW)

Row
-----------------------------------------------------------------------

### Histogram

```{r}
base = ggplot(data=mapWorldVars) + theme_classic()
ps1=base + geom_histogram(aes(x=HDI)) 
ps1
```


### boxplot 

```{r}
ps2=base + geom_boxplot(aes(y= mil_expend)) 
ps2
```

[comment]: # (Plots appear by ROW)

Row
-----------------------------------------------------------------------

### Scatter Plot 1

```{r}
ps3=base + geom_point(aes(x=HDI,y= mil_expend)) 
ps3
```

### Scatter Plot 2

```{r}
ps4=base + geom_point(aes(x=HDI,y= DemoIndex)) 
ps4
```
[comment]: # (THIS CREATES A TAB)


Interactive Plots
=======================================================================

[comment]: # (Plots appear by ROW)

Row
-----------------------------------------------------------------------

### Histogram 

```{r}
pi1=base + geom_histogram(aes(x=HDI)) 
ggplotly(pi1)
```

### Boxplot

```{r}
pi2=base + geom_boxplot(aes(y=DemoIndex)) 
ggplotly(pi2)

```

[comment]: # (Plots appear by ROW)

Row
-----------------------------------------------------------------------

### Scatter Plot 1

```{r}
pi3=base + geom_point(aes(x=HDI,y= mil_expend)) 

ggplotly(pi3)
```

### Scatter Plot 2

```{r}
pi4=base + geom_point(aes(x=HDI,y= DemoIndex))


ggplotly(pi4)
```