---
title: "Dashboards at EVANS UW"
author: "Great student"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed # share your code?
---

```{r setup, include=FALSE}
library(flexdashboard)
###
library(ggplot2)
library(plotly)
library(plyr)
library(sf)

myWeb="https://github.com/EvansDataScience/VAforPM_Dashboard/raw/main/"
worldMap=read_sf(paste0(myWeb,"worldMap.geojson"))
SafeCityPoints=read_sf(paste0(myWeb,"SafeCityPoints.geojson"))
vars=readRDS(file=url(paste0(myWeb,"dataCSV.rds")))
worldMapVars=merge(worldMap,vars,by='ISO3')
```

Static Plots
=======================================================================

Row
-----------------------------------------------------------------------

### Histogram

```{r}
base1 = ggplot(data=vars) + theme_classic()
staticHist=base1 + geom_histogram(aes(x=HDI)) 
staticHist
```


### boxplot 

```{r}
staticBox=base1 + geom_boxplot(aes(y= mil_expend)) 
staticBox
```

Row
-----------------------------------------------------------------------

### Scatter Plot 1

```{r}
staticPoints1=base1 + geom_point(aes(x=HDI,y= mil_expend)) 
staticPoints1
```

### Scatter Plot 2

```{r}
staticPoints2=base1 + geom_point(aes(x=HDI,y= DemoIndex)) 
staticPoints2
```

Interactive Plots
=======================================================================

Row
-----------------------------------------------------------------------

### Histogram 

```{r}
ggplotly(staticHist)
```

### Boxplot

```{r}
ggplotly(staticBox)

```

Row 
-----------------------------------------------------------------------

### Scatter Plot 1

```{r}
ggplotly(staticPoints1)
```

### Scatter Plot 1

```{r}
ggplotly(staticPoints2)
```

Interactive Maps
=======================================================================


Row 
-----------------------------------------------------------------------

### Map 1


```{r}
#the text  aesthetics is NOT for ggplot

base2=ggplot(data=worldMap) + geom_sf(fill='grey90',color=NA) + theme_void()
numericMap= base2 + geom_sf(data=worldMapVars,aes(fill=DemoIndex,
                           text=Country),
                       color=NA)

numericMap=numericMap + scale_fill_gradient(low = 'red',
                                    high= 'blue')
numericMap%>%ggplotly()
```

### Map 2
```{r}
#the text  aesthetics is NOt for ggplot
categoricalMap= base2 + geom_sf(data=worldMapVars,aes(fill=cluster,
                           text=Country),
                       color=NA)

categoricalMap=categoricalMap +  scale_fill_brewer(palette ='YlOrRd',direction = -1)
categoricalMap%>%ggplotly()
```

Row 
-----------------------------------------------------------------------

### Map 2

```{r, eval=TRUE,warning=FALSE,message=FALSE}
basep=ggplot(data = worldMapVars) + geom_sf(fill='grey90',color=NA) + theme_bw()

points1=basep + geom_sf(data=SafeCityPoints,
                       aes(text=city))
points1%>%ggplotly()
```